### ISSUE TITLE
Add multi row for DocumentDetail in Screen Sales Order SO301000

### ISSUE THREAD

**Issue by kimthuy** [ChrisFrench/XCartAcumaticaSync#1]
Hi,

I make a demo site with your code example to submit a new Sales Order and then I have a problem here, Could you give me any idea?

$SO301000Submit->commands = array
            (
                $acumatica->prepareValue("SO", $SO301000GetSchema->OrderSummary->OrderType),
                $acumatica->prepareValue("<NEW>", $SO301000GetSchema->OrderSummary->OrderNbr),
                $acumatica->prepareValue("ACTIVESTAF", $SO301000GetSchema->OrderSummary->Customer),

```
            $SO301000GetSchema->DocumentDetails->ServiceCommands->NewRow,
            $acumatica->prepareValue("AALEGO500", $SO301000GetSchema->DocumentDetails->InventoryID, true),
            $acumatica->prepareValue("HQ", $SO301000GetSchema->DocumentDetails->Branch),

            $SO301000GetSchema->DocumentDetails->ServiceCommands->NewRow,
            $acumatica->prepareValue("AAPOWERAID", $SO301000GetSchema->DocumentDetails->InventoryID, true),
            $acumatica->prepareValue("VA", $SO301000GetSchema->DocumentDetails->Branch),

            $SO301000GetSchema->Actions->Save
        );
```

**Then it return the Exception:**

System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PX.Api.SyImportContext.ParseCommand(SyCommand cmd)
   at PX.Api.SyExportContext.ParseCommand(SYMappingField field)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PX.Api.SyExportContext..ctor(SYMapping mapping, IEnumerable`1 fields, String[] providerFields, Dictionary`2 viewFilters, Boolean breakOnError, Int32 start, Int32 count, Dictionary`2 selectorViews, String rowFilterField)
   at PX.Api.ScreenUtils.Submit(String screenId, Command[] commands, SchemaMode schemaMode, PXGraph& graph, String& redirectContainerView, String& redirectScreen, Boolean mobile, Dictionary`2 viewFilters)
   at PX.Api.Services.ScreenService.Submit(String id, IEnumerable`1 commands, SchemaMode schemaMode, Boolean mobile, PXGraph& forceGraph, String& redirectContainerView, String& redirectScreen, Dictionary`2 viewFilters)
   at PX.Api.Services.ScreenService.Submit(String id, IEnumerable`1 commands, SchemaMode schemaMode)
   at PX.Api.Soap.Screen.ScreenGate.Submit(Command[] commands)

**If I just insesrt only one DocumentDetail -> it work ok**

$SO301000Submit->commands = array
            (
                $acumatica->prepareValue("SO", $SO301000GetSchema->OrderSummary->OrderType),
                $acumatica->prepareValue("<NEW>", $SO301000GetSchema->OrderSummary->OrderNbr),
                $acumatica->prepareValue("ACTIVESTAF", $SO301000GetSchema->OrderSummary->Customer),

```
            $SO301000GetSchema->DocumentDetails->ServiceCommands->NewRow,
            $acumatica->prepareValue("AALEGO500", $SO301000GetSchema->DocumentDetails->InventoryID, true),
            $acumatica->prepareValue("HQ", $SO301000GetSchema->DocumentDetails->Branch),

            $SO301000GetSchema->Actions->Save
        );
```

**Please help me .**

**Comment by ChrisFrench** [comment]
Sorry this was a one off project that I put up to be helpful. I don't support acumatica or xcart

**Comment by kimthuy** [comment]
Oh, I will solve it by myself.
Anyway, thank-you so much.
